import streamlit as st
import subprocess

OLLAMA_MODEL = "phi3"


def ask_ollama(prompt):
    try:
        result = subprocess.run(
            ["ollama", "run", OLLAMA_MODEL],
            input=prompt,
            text=True,
            capture_output=True
        )
        if result.stdout.strip():
            return result.stdout.strip()
        else:
            return "No response generated by the model."
    except Exception:
        return "Error: Unable to connect to local AI model."


def run():
    st.subheader("Email Writer Agent")

    st.write(
        "Generate professional and student-friendly emails for academic "
        "and workplace communication."
    )

    email_type = st.selectbox(
        "Select Email Purpose",
        [
            "Meeting Request",
            "Follow-up Email",
            "Leave / Permission Request",
            "Apology Email",
            "Professional Introduction",
            "Custom Email"
        ]
    )

    tone = st.selectbox(
        "Select Tone",
        ["Formal", "Friendly", "Urgent"]
    )

    context = st.text_area(
        "Provide context / key points for the email",
        placeholder=(
            "Example:\n"
            "Requesting a meeting with project guide regarding final review.\n"
            "Preferred date: 12 Jan.\n"
            "Time: 3 PM."
        )
    )

    recipient = st.text_input(
        "Recipient (optional)",
        placeholder="e.g., Professor / Manager / HR"
    )

    if st.button("Generate Email"):
        if not context.strip():
            st.warning("Please provide context for the email.")
            return

        prompt = f"""
You are an expert professional email writer.

Write a {tone.lower()} {email_type.lower()} email.

Recipient: {recipient if recipient else "Not specified"}

Context:
{context}

Guidelines:
- Use clear subject line
- Maintain professional tone
- Keep it concise
- Proper greeting and closing

Return ONLY the email content.
"""

        with st.spinner("Generating email..."):
            email = ask_ollama(prompt)

        st.markdown("### Generated Email")
        st.text_area(
            "You can copy and edit before sending",
            email,
            height=300
        )
